### ISSUE TITLE
Does not build with ionic 2 webpak

### ISSUE THREAD

**Issue by hazeem1991** [inorganik/countUp.js#156] opened 2017-03-20 09:27 UTC
__WEBPACK_IMPORTED_MODULE_13_countup_js_countUp_js__.CountUp
TypeError: __WEBPACK_IMPORTED_MODULE_13_countup_js_countUp_js__.CountUp is not a constructor
    at SafeSubscriber._next (VM16516 main.js:87268)
    at SafeSubscriber.__tryOrUnsub (VM16516 main.js:1409)
    at SafeSubscriber.next (VM16516 main.js:1358)
    at Subscriber._next (VM16516 main.js:1300)
    at Subscriber.next (VM16516 main.js:1264)
    at MapSubscriber._next (VM16516 main.js:70046)
    at MapSubscriber.Subscriber.next (VM16516 main.js:1264)
    at XMLHttpRequest.onLoad (VM16516 main.js:84223)
    at t.invokeTask (VM16460 polyfills.js:3)
    at Object.onInvokeTask (VM16516 main.js:40451)
    at t.invokeTask (VM16460 polyfills.js:3)
    at e.runTask (VM16460 polyfills.js:3)
    at XMLHttpRequest.invoke (VM16460 polyfills.js:3)
Ionic Framework: ^2.2.0
Ionic Native: ^2.9.0
Ionic App Scripts: 1.1.4
Angular Core: ^2.4.10
Angular Compiler CLI: ^2.4.10
Node: 7.5.0
OS Platform: Windows 10
Navigator Platform: Win32

**Comment by inorganik** [comment] 2017-03-20 16:09
I believe this is a duplicate of #154

**Comment by inorganik** [comment] 2017-08-23 23:16
Closing this, since the Angular 2 module has moved into [its own repo](https://github.com/inorganik/countUp.js-angular2) as of v1.9.0. Please open any issues you have there.

**Closed by inorganik** 2017-08-23 23:16 UTC
