### ISSUE TITLE
Something missing in order to run with Ionic 2

### ISSUE THREAD

**Issue by dacodemaniak** [inorganik/countUp.js#169] opened 2017-05-22 14:03 UTC
Hi all,
Try to add countUp in my Ionic 2 Cordova development and i'm unable to create the component...

Steps i do

- first added the module in my app.module.ts this way 

    import { CountUpModule } from '../../node_modules/countup.js/countUp.module';

- Add in @NgModule, in the imports 'CountupModule'

- In app.module.ts, added the Component and export this way 
@Component({
  selector: 'count-up',
   template: `
        <h3 countUp="{useEasing: false}"
            [startVal]="myStartVal"
            [endVal]="myEndVal"
            [reanimateOnClick]="false"></h3>
   `
})
export class CountingHeaderComponent {
    @Input()
    myStartVal: number;

    @Input()
    myEndVal: number;
}

But i don't know how to integrate the component in any view... try <h2 count-up ....></h2>
and nothing appears...

What i'm doing wrong ?

Thx...

JL

**Comment by inorganik** [comment] 2017-05-24 14:36
Possible duplicate of #154

**Comment by inorganik** [comment] 2017-08-23 23:16
Closing this, since the Angular 2 module has moved into [its own repo](https://github.com/inorganik/countUp.js-angular2) as of v1.9.0. Please open any issues you have there.

**Closed by inorganik** 2017-08-23 23:16 UTC
