### ISSUE TITLE
Crash when resetting a counter with decimal places

### ISSUE THREAD

**Issue by lukaszsamson** [inorganik/countUp.js#155] opened 2017-03-15 12:52 UTC
After setting a countup with decimal places, the final value is formatted to string. A subsequent call to reset crashes because nStr is a string not a number in formatNumber

Stacktrace:

TypeError: nStr.toFixed is not a function
    at CountUp.self.formatNumber
    at CountUp.self.printValue
    at CountUp.self.reset
    at CountUpDirective.animate
    at CountUpDirective.ngOnInit

**Comment by inorganik** [comment] 2017-03-15 15:17
When you call `reset()`, it passes your `startVal` to `self.formattingFn`, (which defaults to `formatNumber()`). The only way I could reproduce this is if I passed an empty string as the start value, which must be what you've done.

You must pass a number as the startVal. Can you please elaborate on your case? Say exactly what you did and how you did it.

**Comment by lukaszsamson** [comment] 2017-03-15 15:26
No, I init it with a  valid number.
I have the element inside an `*ngIf="condition"`. The failing call to `reset()` happens when Angular re-renders the element after the sequence
`condition = false`
`condition = true`

I hope it helps.

**Comment by inorganik** [comment] 2017-03-15 15:52
Try this: Paste this code just before the return statement in `createCountUp` function in `angular-countUp.js`

```js
console.log('createCountUp -------');
console.log('starVal', typeof sta, sta);
console.log('endVal', typeof end, end);
```

Let us know the result.

**Comment by inorganik** [comment] 2017-03-15 16:19
Updated the test above to use `isNaN()` instead of typeof, since typeof will still say 'number' for NaN.

**Comment by lukaszsamson** [comment] 2017-03-15 17:11
//`condition = true`
createCountUp -------
starVal false 0
endVal false 2.8828150
//`condition = false`
...
//`condition = true`
createCountUp -------
starVal false 2.8828150
endVal false 2.8828150
EXCEPTION: nStr.toFixed is not a function...

debugging it I can see that the value gets corrupted in `reset()` line
`self.startVal = startVal;`
The closure variable is somehow a string. I suspect some typescript or angular compiler shenanigans.

However, adding simple
`if (typeof nStr === 'number') {
            nStr = nStr.toFixed(self.decimals);
            nStr += '';
}`
in `formatNumber` fixes the exception in my case

**Comment by inorganik** [comment] 2017-03-15 17:21
Currently when you initialize countUp, it sets `self.startVal = Number(startVal);`. 

When you call reset(), it sets `self.startVal = startVal;`. 

I'm working on a change to use an intialize() function which gets called in both cases. It also will do error checks, which should solve your issue. I'll close this when I make the update.

**Comment by inorganik** [comment] 2017-03-16 16:08
Please pull latest (v1.8.3) @lukaszsamson and your issue should be fixed.

**Closed by inorganik** 2017-03-16 16:08 UTC
