### ISSUE TITLE
Demo not working on IE 11

### ISSUE THREAD

**Issue by HDeiro** [inorganik/countUp.js#238] opened 2020-07-06 17:15 UTC
```
[x] Bug
[ ] Feature request

CountUp.js version:

```

## Description
I wasn't able to run the demo in Internet Explorer.

I didn't tested the lib. But, considering the demo didn't ran correctly, I think the same should be happening in the lib also.

Just tried to open the [demo link](https://inorganik.github.io/countUp.js/) on Internet Explorer 11 (Version 11.285.17134.0) and it didn't worked.

I tried to check the console to provide more accurate info, but didn't found any error logs.

**Comment by inorganik** [comment] 2020-07-06 17:26
Thank you! I will look into it.

**Comment by inorganik** [comment] 2020-07-06 17:39
I believe the problem is that [IE11 doesn't support ES6 modules](https://caniuse.com/#search=es6%20modules), which the demo uses. The lib will still work if you include it a different way. I will push up a fix soon.

**Comment by inorganik** [comment] 2020-07-06 18:05
Try now? (make sure to refresh)

**Comment by HDeiro** [comment] 2020-07-06 18:38
Hey. Sorry for the delay, I was busy doing some stuff.

Well... I agree that it might be an issue on ES6 Modules. Have you tried to add some polyfills? 

I just tested here. Still not working, but at least there is an error now: 

![image](https://user-images.githubusercontent.com/6384551/86627402-a5770480-bf9e-11ea-849e-159be2019397.png)

**Comment by inorganik** [comment] 2020-07-13 15:29
I got this fixed by using fallback scripts included with `nomodule` script tags. Tested in a VM. 👍

**Closed by inorganik** 2020-07-13 15:29 UTC

**Comment by HDeiro** [comment] 2020-07-13 17:26
Validated here. No longer an issue.
